// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvzfpknpccrakrultvvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2emZwa25wY2NyYWtydWx0dnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MTY1NzksImV4cCI6MjA2Nzk5MjU3OX0.8JWn8MzyU4vrucXu_kwNF2EJp6eZdK0j2ajsZBCfgAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});